### ISSUE TITLE
Move custom place field from init to within place form - so that it isn't saved in place doc

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-configurer#21]
Rationale: we need to show this field in the place group only when relevant, so cannot fully replace the place's name field. Having it there full time would mean having a non-relevant field saved with the place, which is a duplicate field and possibly junk.

Currently done crudely at https://github.com/medic/medic-projects/blob/3f6671f79b1763d45e5faab87cea8e4b7ce5aae8/standard/forms/process_place_forms.sh#L82-L86

**Comment by alxndrsn** [comment]
@abbyad the linked `sed` command seems to move input fields around in the form, whereas the title of the ticket implies that there should be changes to the `<model>` happening.  Which is correct?

**Comment by alxndrsn** [comment]
@abbyad I think this would be fixed by https://github.com/medic/medic-configurer/commit/e075ef91c65ad0c43d01756e1005388f99116da0.  Please check the XML changes in that commit, and see if they match your expectations.

**Comment by abbyad** [comment]
Ya, that title could be interpreted several ways. Currently we have the custom name field in `init` and moving the UI element to the place group. The reason we have it in `init` and not in the place group initially in XLSX and model is to avoid having that field saved with the place.

It may make more sense for it to be in the place group in the XLSX then moved in the model since that would be clearer to a person creating/editing the form where elements are displayed in the form. I'll check the commit and we can discuss from there if anything needs to be changed.

**Comment by abbyad** [comment]
The create form in that commit looks good. The edit form has since changed and it does not have a `custom_place_name` field anymore, and it does not need any field relocation.
