### ISSUE TITLE
Handle templated contact/place forms

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-configurer#4]
The forms `PLACE_TYPE-create.xlsx`, `PLACE_TYPE-edit.xlsx` need to be converted to:
- `clinic-create.xml`
- `clinic-edit.xml`
- `district_hospital-create.xml`
- `district_hospital-edit.xml`  
- `health_center-create.xml`
- `health_center-edit.xml`

The only difference between them is that `PLACE_TYPE` and `PLACE_NAME` are replaced differently.

The XForm also has some custom edits to work as a place form and create the contact properly:

- Move place to above person (in data model, due to XML ordering mattering, even though it shouldn't: https://github.com/medic/medic-webapp/issues/1494)
- Move custom place field from init to within place form - so that it isn't saved in place doc
- Move new contact person to first page - move the group inside previous group
- Add space after output field https://github.com/medic/medic-webapp/issues/3324

The forms at https://github.com/medic/medic-projects/tree/master/standard/forms are fully generated by this convention, so tests could be created based around the xlsx and forms in that project.

**Comment by alxndrsn** [comment]
# Implementation

1. Create `forms/contact/PLACE_TYPE-create.xlsx`
2. Create `forms/contact/PLACE_TYPE-edit.xlsx`
3. Create `forms/contact/place-types.json`:
```
{
  "clinic": "Clinic",
  "district_hostpital": "District Hostpital",
  "health_center": "Health Center"
}
```

4. run `medic-conf convert-contact-forms` as before, and the relevant xforms will be created from the templates.

@abbyad does this look suitable?  If you want a way to share template xlsx between projects, this could easily be added.  E.g. by changing the JSON file like so:
```
{
  "templates": "../standard/forms/contact",
  "types": {
    "clinic": "Clinic",
    "district_hostpital": "District Hostpital",
    "health_center": "Health Center"
  }
}
```

**Comment by alxndrsn** [comment]
Released in version `1.5.6`.

**Comment by abbyad** [comment]
Overall this works great, and is a nice improvement over having to do this step manually!

Reopening since these don't seem to be done:
- Move custom place field from init to within place form - so that it isn't saved in place doc
  - Rational: we need to show this field in the place group only when relevant, so cannot fully replace the place's name field. Having it there full time would mean having a non-relevant field saved with the place, which is a duplicate field and possibly junk.
  - Currently done crudely [here](https://github.com/medic/medic-projects/blob/3f6671f79b1763d45e5faab87cea8e4b7ce5aae8/standard/forms/process_place_forms.sh#L82-L86)
- Move new contact person to first page - move the group inside previous group
  - Rational: we want to show the new contact fields below the "Select Primary Contact" question, not on a separate page.
  - Currently done crudely [here](https://github.com/medic/medic-projects/blob/3f6671f79b1763d45e5faab87cea8e4b7ce5aae8/standard/forms/process_place_forms.sh#L88-L95)

**Comment by alxndrsn** [comment]
Filed separately at https://github.com/medic/medic-configurer/issues/21 and https://github.com/medic/medic-configurer/issues/22
